org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:HeapBaseMinAddress=0x100000000 -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableR8.fullMode=false
